### PR TITLE
4 about us page

### PR DESCRIPTION
**Pull request by thecowsays**
Resolved some conflicts on my local repo due to the deletion of branches setup previously (outdated deletions).

This is a pull requesting code review to ensure nothing on the main branch gets changed during this merge.

### CODE REVIEW

**Review by thecowsays — COMMENTED** [review]
Most of the changes are simple whitespacing, **I see no code changes, good to merge.**

**Comment by thecowsays** [comment]
No actual code changes, simply whitespacing and nesting issues fixed or adjusted for the better.

**Review by MidnightFlamingo97 — CHANGES_REQUESTED** [review]
Not sure what happened here, but there is too much error for this to be pushed to main. Sorry!

**Comment by thecowsays** [comment]
Closing. Deleting local files and attempting new pull without conflicts.

**Pull request closed without merging**
